/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uw2l;

/**
 *
 * @author harri
 */
public class theVP extends javax.swing.JFrame {

    /**
     * Creates new form theVP
     */
    public theVP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vidPanel1 = new javax.swing.JPanel();
        playVPBtn = new javax.swing.JButton();
        skopVPBtn = new javax.swing.JButton();
        pauseVPBtn = new javax.swing.JButton();
        rewindVPBtn = new javax.swing.JButton();
        skipVPBtn = new javax.swing.JButton();
        filenameL1 = new javax.swing.JLabel();
        playingVP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playVPBtn.setText("play");

        skopVPBtn.setText("stop");

        pauseVPBtn.setText("pause");

        rewindVPBtn.setText("rewind");

        skipVPBtn.setText("skip");

        filenameL1.setText("filename");

        javax.swing.GroupLayout playingVPLayout = new javax.swing.GroupLayout(playingVP);
        playingVP.setLayout(playingVPLayout);
        playingVPLayout.setHorizontalGroup(
            playingVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        playingVPLayout.setVerticalGroup(
            playingVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vidPanel1Layout = new javax.swing.GroupLayout(vidPanel1);
        vidPanel1.setLayout(vidPanel1Layout);
        vidPanel1Layout.setHorizontalGroup(
            vidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vidPanel1Layout.createSequentialGroup()
                .addGroup(vidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vidPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(playVPBtn)
                        .addGap(32, 32, 32)
                        .addComponent(skopVPBtn)
                        .addGap(37, 37, 37)
                        .addComponent(pauseVPBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rewindVPBtn)
                        .addGap(18, 18, 18)
                        .addComponent(skipVPBtn))
                    .addGroup(vidPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vidPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(playingVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filenameL1))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        vidPanel1Layout.setVerticalGroup(
            vidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vidPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(filenameL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playingVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(vidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playVPBtn)
                    .addComponent(skopVPBtn)
                    .addComponent(pauseVPBtn)
                    .addComponent(rewindVPBtn)
                    .addComponent(skipVPBtn))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theVP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filenameL1;
    private javax.swing.JButton pauseVPBtn;
    private javax.swing.JButton playVPBtn;
    private javax.swing.JPanel playingVP;
    private javax.swing.JButton rewindVPBtn;
    private javax.swing.JButton skipVPBtn;
    private javax.swing.JButton skopVPBtn;
    private javax.swing.JPanel vidPanel1;
    // End of variables declaration//GEN-END:variables
}
